- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: python.yaml
  ansible.builtin.import_role:
   name: common
   tasks_from: python


- name: systemd restart
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd
