- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: go
  ansible.builtin.import_role:
   name: common
   tasks_from: go



- name: systemd restart
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd