- name: create user 
  ansible.builtin.user:
    name: roboshop

- name: remove directory
  ansible.builtin.file:
    path: /app
    state: absent
  
- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download file 
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{variable}}.zip
    dest: /tmp

- name: unzip downloaded file
  ansible.builtin.unarchive:
    src: /tmp/{{variable}}.zip
    dest: /app
    remote_src: yes