- name: install mysql
  ansible.builtin.dnf:
   name: mysql
   state: present

- name: load schema
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/{{variable}}.sql 

